name: Notify CI
on:
  schedule:
    - cron:  '5 1 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Use Node.js 16.15.1
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.1
        cache: 'pnpm'
    
    - name: Install Deps
      run: pnpm i
    
    - name: Build
      run: npx tsc
    
    - name: Notify news
      run: node dist/app.js